services:
  - docker
matrix:
  include:
    - language: php
      name: "7.4"
      after_script:
        - sh .travis.coverage.sh
      env:
        - COVERAGE_FLAGS="--coverage-text --coverage-clover=build/clover.xml"

before_script:
  - docker build --build-arg PHP_VERSION=${TRAVIS_JOB_NAME} -t z-engine .
script:
  - docker run z-engine /usr/src/z-engine/vendor/bin/phpunit --verbose ${COVERAGE_FLAGS} --colors --exclude-group=internal
